### PR TITLE
Fix possible NullPointerException in InstanceActionHandler

### LINKED ISSUE #31: Possible NullPointerException in InstanceActionHandler
After introducing the 'slaAware' field in [this commit](https://github.com/apache/aurora/commit/4e28e73bb83b75f1369a705d15c96e40fb7098e1), there has been a possible NullPointerException in [this line](https://github.com/apache/aurora/blob/master/src/main/java/org/apache/aurora/scheduler/updater/InstanceActionHandler.java#L210). This happens when an update only kills instances. There is no `desiredState`, so `getDesiredState().getTask()` will try to act on a null object. Other places in the code guard against this case by checking `isSetDesiredState()` before retrieval.

We should properly handle nulls in this case, and add generic end to end tests for only adding instances and only removing instances with updates.

### PR DESCRIPTION
**Pull request by jordanly**
Fixes #31 for a description of the issue.

Ensure that we properly handle possible null values when checking the SlaPolicy of an update. Added e2e tests to prevent regression and test commonly-used code paths. Validated that currently master does not pass the tests but the patch provided does.

### CODE REVIEW

File: src/test/sh/org/apache/aurora/e2e/test_end_to_end.sh [hunk 1]
```diff
@@ -223,6 +223,17 @@ assert_update_state() {
   fi
 }
 
+assert_update_id_state() {
```
Comment (shanmugh) [inline src/test/sh/org/apache/aurora/e2e/test_end_to_end.sh]: s/assert_update_id_state/assert_update_state/
